name: Export cache

on:
  schedule:
  - cron: "0 0 6 * *"
  workflow_dispatch:

jobs:
  export_cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - '25.12'

    steps:
      - name: Cache ${{ matrix.branch }} DL dependencies
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/DL # MUST same with compile.yml # https://github.com/actions/cache/issues/1653
          key: Cache-DL-${{ matrix.branch }}-
          restore-keys: |
            Cache-DL-${{ matrix.branch }}-
      - name: Compress DL Cache
        run: |
          pushd ${{ github.workspace }}/DL
          tar -I zstd -cf /${{ github.workspace }}/DL.tzst * --owner=0 --group=0 --no-same-owner --no-same-permissions || echo "No files to compress"
          popd
      - name: Upload DL Cache artifact
        uses: actions/upload-artifact@v6
        with:
          name: DL-${{ matrix.branch }}.tzst
          path: ${{ github.workspace }}/DL.tzst
          retention-days: 90
