name: Export cache

on:
  schedule:
  - cron: "0 0 6 * *"
  workflow_dispatch:

jobs:
  export_cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - '24.10'

    steps:
      - name: Initialize Environment
        run: |
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          mkdir -p /workdir/DL
      - name: Cache ${{ matrix.branch }} DL dependencies
        uses: actions/cache/restore@v4
        with:
          path: /workdir/DL
          key: Cache-DL-${{ matrix.branch }}-
          restore-keys: |
            Cache-DL-${{ matrix.branch }}-
      - name: Compress DL Cache
        run: |
          pushd /workdir/DL
          tar -I zstd -cf /workdir/DL.tzst * --owner=0 --group=0 --no-same-owner --no-same-permissions || echo "No files to compress"
          popd
      - name: Upload DL Cache artifact
        uses: actions/upload-artifact@v5
        with:
          name: DL-${{ matrix.branch }}.tzst
          path: /workdir/DL.tzst
          retention-days: 1
