name: Simptest

on:
  workflow_dispatch:
    inputs:
      PACKAGES:
        required: true
        type: string
      OP_VERSION:
        required: true
        default: '23.05.5'
        type: string
      BOARD:
        required: true
        default: 'x86'
        type: string
      SUBTARGET:
        required: true
        default: '64'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch

    steps:
      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        shell: bash
        run: |
          sudo apt update
          sudo apt -y install axel build-essential ccache clang curl flex bison g++ gawk \
          gcc-multilib g++-multilib genisoimage gettext git libdw-dev libelf-dev \
          libncurses5-dev libssl-dev locales pv pwgen python3 python3-pip \
          python3-setuptools qemu-utils rsync signify-openbsd subversion swig unzip \
          zlib1g-dev file wget zstd python3-pyelftools \
          clang llvm libbpf-dev pkg-config libdw-dev libelf-dev zlib1g-dev

      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
          lfs: true
          submodules: true

      - name: mkdir WORKDIR
        shell: bash
        run: |
          mkdir -p WORKDIR

      - name: Do Something
        id: do_something
        shell: bash
        run: |
          cd WORKDIR
          echo Do Something

      - name: Setup tmate session
        if: ${{ failure() && steps.do_something.conclusion == 'failure' }}
        uses: mxschmitt/action-tmate@v3

      - name: Upload WORKDIR
        if: ${{ failure() && steps.do_something.conclusion == 'failure' }}
        uses: actions/upload-artifact@v5
        with:
          name: do_something-${{ hashFiles('**/Makefile') }}
          path: ${{ github.workspace }}/WORKDIR
          compression-level: 9
          include-hidden-files: true
